export const notifications = [
  {
    id: 'NOTI-1001',
    title: 'Lịch hẹn test đầu vào sắp diễn ra',
    summary: 'Nguyễn Minh Anh có lịch test lúc 09:30 tại Room 3.',
    content: 'Ứng viên Nguyễn Minh Anh có lịch test đầu vào lúc 09:30 tại Room 3. Vui lòng chuẩn bị hồ sơ tư vấn, phiếu đánh giá trình độ và nhắc phụ huynh đến trước 10 phút.',
    time: '08:15',
    category: 'Lịch hẹn',
    tone: 'orange',
    unread: true,
  },
  {
    id: 'NOTI-1002',
    title: 'Ứng viên mới từ Facebook Ads',
    summary: 'Có 12 ứng viên mới cần gọi tư vấn trong hôm nay.',
    content: 'Chiến dịch Facebook Ads vừa ghi nhận 12 ứng viên mới. Hãy ưu tiên gọi trong khung giờ 09:00 - 11:30 và cập nhật kết quả chăm sóc vào hệ thống.',
    time: '07:45',
    category: 'Ứng viên tiềm năng',
    tone: 'green',
    unread: true,
  },
  {
    id: 'NOTI-1003',
    title: 'Nhắc cập nhật kết quả test',
    summary: '3 bài test đầu vào đang chờ đánh giá.',
    content: 'Hiện có 3 bài test đầu vào đang ở trạng thái chờ đánh giá. Vui lòng kiểm tra điểm, gợi ý khóa học phù hợp và chuyển trạng thái sau khi tư vấn.',
    time: 'Hôm qua',
    category: 'Kiểm tra đầu vào',
    tone: 'amber',
    unread: false,
  },
  {
    id: 'NOTI-1004',
    title: 'Hồ sơ cá nhân cần rà soát',
    summary: 'Cập nhật số điện thoại và chi nhánh phụ trách nếu có thay đổi.',
    content: 'Bạn nên rà soát hồ sơ cá nhân định kỳ để đảm bảo thông tin liên hệ, chi nhánh phụ trách và vai trò hiện tại luôn chính xác.',
    time: 'Thứ 2',
    category: 'Hồ sơ cá nhân',
    tone: 'slate',
    unread: false,
  },
]
