export const placementTestCatalog = [
  {
    id: 'A1',
    level: 'A1',
    title: 'Starter Check',
    duration: '15 phút',
    recommendation: 'Kids Starter',
    questions: [
      { question: 'Choose the correct word: This ___ my book.', options: ['am', 'is', 'are', 'be'], answer: 1 },
      { question: 'What color is the sky on a sunny day?', options: ['Blue', 'Green', 'Black', 'Brown'], answer: 0 },
      { question: 'Choose the plural: one child, two ___', options: ['childs', 'children', 'childes', 'child'], answer: 1 },
      { question: 'I go to school ___ Monday.', options: ['in', 'at', 'on', 'to'], answer: 2 },
      { question: 'What is the opposite of big?', options: ['Small', 'Tall', 'Fast', 'Long'], answer: 0 },
    ],
  },
  {
    id: 'A2',
    level: 'A2',
    title: 'Foundation Check',
    duration: '20 phút',
    recommendation: 'IELTS Foundation',
    questions: [
      { question: 'She ___ English every evening.', options: ['study', 'studies', 'studying', 'studied'], answer: 1 },
      { question: 'Choose the correct sentence.', options: ['I have ever been to Da Nang.', 'I have been to Da Nang.', 'I has been to Da Nang.', 'I been to Da Nang.'], answer: 1 },
      { question: 'If it rains, we ___ at home.', options: ['stay', 'stayed', 'will stay', 'staying'], answer: 2 },
      { question: 'The movie was ___ than I expected.', options: ['interesting', 'more interesting', 'most interesting', 'interest'], answer: 1 },
      { question: 'Choose the best response: "How often do you read?"', options: ['Yesterday', 'Twice a week', 'At school', 'Because I like it'], answer: 1 },
    ],
  },
  {
    id: 'B1',
    level: 'B1',
    title: 'Intermediate Check',
    duration: '25 phút',
    recommendation: 'IELTS Intermediate',
    questions: [
      { question: 'By the time we arrived, the class ___.', options: ['starts', 'started', 'had started', 'will start'], answer: 2 },
      { question: 'Choose the closest meaning of "reliable".', options: ['Trustworthy', 'Expensive', 'Difficult', 'Temporary'], answer: 0 },
      { question: 'He suggested ___ earlier for the test.', options: ['arrive', 'arriving', 'to arrive', 'arrived'], answer: 1 },
      { question: 'The report ___ by the teacher yesterday.', options: ['checked', 'was checked', 'is checking', 'checks'], answer: 1 },
      { question: 'Choose the best connector: I was tired; ___, I finished the essay.', options: ['however', 'because', 'although', 'unless'], answer: 0 },
    ],
  },
  {
    id: 'B2',
    level: 'B2',
    title: 'Upper Intermediate Check',
    duration: '30 phút',
    recommendation: 'Business Communication',
    questions: [
      { question: 'Had I known about the delay, I ___ earlier.', options: ['leave', 'left', 'would have left', 'will leave'], answer: 2 },
      { question: 'Choose the best paraphrase: "The policy is likely to be revised."', options: ['It cannot change.', 'It will probably be changed.', 'It was already changed.', 'It should never change.'], answer: 1 },
      { question: 'The speaker\'s argument was convincing, ___ some evidence was missing.', options: ['even though', 'therefore', 'so that', 'in case'], answer: 0 },
      { question: 'Choose the word closest to "substantial".', options: ['Minor', 'Considerable', 'Optional', 'Brief'], answer: 1 },
      { question: 'Not only ___ the task, but she also improved the process.', options: ['completed she', 'she completed', 'did she complete', 'she did complete'], answer: 2 },
    ],
  },
  {
    id: 'IELTS-4.5',
    level: 'IELTS 4.5',
    title: 'IELTS Placement',
    duration: '35 phút',
    recommendation: 'IELTS Intermediate',
    questions: [
      { question: 'In IELTS Writing Task 2, a clear position should be presented in the ___.', options: ['footnote', 'introduction', 'reference list', 'page number'], answer: 1 },
      { question: 'Choose the best academic word: The chart ___ an increase in sales.', options: ['shows', 'talks', 'says', 'makes'], answer: 0 },
      { question: 'Which phrase is best for comparing data?', options: ['In contrast', 'By the way', 'At home', 'For fun'], answer: 0 },
      { question: 'Choose the best collocation.', options: ['make a decision', 'do a decision', 'take a homework', 'make a mistake of homework'], answer: 0 },
      { question: 'A thesis statement usually tells the reader the writer\'s ___.', options: ['address', 'main opinion', 'score', 'password'], answer: 1 },
    ],
  },
]
